Workaround Swift Package Manager Resolution Restriction (#6)
Fixes #1 

This PR addresses the package resolution issue when this package is
included as a dependency in SPM:

```
Running resolver because the following dependencies were added: 'kaleidoscope-lexer' (https://github.com/FlickerSoul/kaleidoscope-lexer)
error: Dependencies could not be resolved because root depends on 'kaleidoscope-lexer' 0.1.0..<1.0.0.
'kaleidoscope-lexer' >= 0.1.0 cannot be used because no versions of 'kaleidoscope-lexer' match the requirement 0.1.1..<1.0.0 and package 'kaleidoscope-lexer' is required using a stable-version but 'kaleidoscope-lexer' depends on an unstable-version package 'swift-experimental-string-processing'.
```

By pulling `swift-experimental-string-processing` as a submodule, the
resolution should succeed.